const records = {
  "Indian Flag": "./assets/Indian Flag.jpeg",
  "Be Yourself": "./assets/Be Yourself.jpeg",
  "Body Builder": "./assets/Body Builder.jpg",
  "Body Building Pose": "./assets/Body Building Pose.jpeg",
  Breathe: "./assets/Breathe.jpeg",
  Demons: "./assets/Demons.jpeg",
  Dubai: "./assets/Dubai.jpeg",
  "Evil Toy": "./assets/Evil Toy.jpeg",
  "Exo Planets": "./assets/Exo Planets.jpg",
  Goku: "./assets/Goku.jpg",
  Hacker: "./assets/Hacker.jpg",
  Halloween: "./assets/Halloween.jpeg",
  "Horrific Hands": "./assets/Horrific Hands.jpeg",
  IT: "./assets/IT.jpeg",
  "Life Quote": "./assets/Life Quote.jpeg",
  Mustang: "./assets/Mustang.jpg",
  "New York": "./assets/New York.jpeg",
  Otter: "./assets/Otter.jpeg",
  Productivity: "./assets/Productivity.jpeg",
  "Work Quote": "./assets/Work Quote.jpeg",
  Scene: "./assets/Scene.jpeg",
  "Silent Quote": "./assets/Silent Quote.jpeg",
  Skull: "./assets/Skull.jpeg",
  Soldier: "./assets/Soldier.jpeg",
  Venom: "./assets/Venom.jpg",
  Green: "./assets/Green.jpeg",
  "Aurora Tree": "./assets/Aurora Tree.jpeg",
  "Big Star": "./assets/Big Image.jpeg",
};

export default records;
